### ISSUE TITLE
Linking Github repos to Respective papers

### ISSUE THREAD

**Issue by rohit-kumar-j** [3DFaceBody/awesome-3dbody-papers#10]
Hi! Can you link github repos or given code or similar code(if any) with the papers that have been listed?
Example: 
Deep Mimic - SIGGRAPH 2018 
https://xbpeng.github.io/projects/DeepMimic/index.html
https://github.com/xbpeng/DeepMimic

**Comment by VVingerfly** [comment]
Hi, @rohit-kumar-j 

The code of each paper (if there exists or perhaps I found) is provided already.

For example, 
![image](https://user-images.githubusercontent.com/16233971/106586807-d5fa3d80-6583-11eb-8ffb-831784940368.png)

The title, [Page] and [Code] are all hyperlinks,
- title links to the pdf or arxiv page of the paper,
- [Page] links to the project homepage of the paper,
- [Code] links to the code of github repo of the paper.

So just click on them :)

B.R.
