### ISSUE TITLE
One item is misclassified

### ISSUE THREAD

**Issue by Tina-Husky** [3DFaceBody/awesome-3dbody-papers#14]
I think "PoseLifter: Absolute 3D Human Pose Lifting Network from a Single Noisy 2D Human Pose. ArXiv, 2020." is misclassified by accident. It should be in "Body Pose", rather than in "Naked Body Mesh".

But I gotta say, it is a neat, comprehensive and thorough collection for 3D Human Body papers. Great job! Undoubtedly!

**Comment by VVingerfly** [comment]
Hi, thanks for pointing out the misclassification, it was corrected now. And thanks for your appreciation, I'm very glad this repo helps. :)
