### ISSUE TITLE
[ECCV 2020] Joint Optimization for Multi-Person Shape Models from Markerless 3D-Scans

### ISSUE THREAD

**Issue by VVingerfly** [3DFaceBody/awesome-3dbody-papers#8]
- http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123630035.pdf
- https://github.com/Intelligent-Systems-Research-Group/JOMS

**Comment by AlexanderMelde** [comment]
Hello Wei Li, i am contacting you on behalf of the authors of above paper and code. We would like to know if you have any questions about our publications and are offering our help to resolve any issues you might have regarding this topic. Kind regards, Alexander from @Intelligent-Systems-Research-Group.

**Comment by VVingerfly** [comment]
Hi @AlexanderMelde 
Nice work, I was planing to add this paper to the list. I'm add it to the category of body model now. 
Thanks for your remind and excellent work!

B.R.
